version: '2'
services:
  calendar:
    container_name: "mcalendar"
    image: golang:latest
    ports:
    - "8080:8080"
    links:
    - mongodb
    depends_on:
    - mongodb
    volumes:
    - ./data/uploads:/uploads
    - ./src:/go/src/gitlab.com/irezaa/calendar/src
    working_dir: /go/src/gitlab.com/irezaa/calendar/src
    command: bash -c "go build -o ./bin/calendar && ./bin/calendar"
    tty: true
  mcalendar/admin:
    container_name : "mcalendar/admin"
    image: python:latest
    ports:
      - "80:80"
    links:
      - mcalendar
      - mongodb
    volumes:
      - ./admin:/src
    working_dir: /src
    command: bash -c "pip install -r /src/requirements.txt && python app.py"
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
    - MONGO_DATA_DIR=/mcalendar/data/db
    - MONGO_LOG_DIR=/dev/null
    volumes:
    - ./data/db:/data/db
    ports:
    - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet