version: '2'
services:
  calendar:
    container_name: "calendar"
    image: reza
    ports:
    - "8080:8080"
    links:
    - mongodb
    depends_on:
    - mongodb
    command: amd64
    volumes:
    - /hellno/reza/data/uploads:/uploads
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    volumes:
    - ./data/db:/data/db
    ports:
    - 27017:27017
    command: mongod --auth --smallfiles --logpath=/dev/null # --quiet