version: '2'
services:
  mcalendar:
    restart: always
    container_name: "mcalendar"
    image: golang:latest
    expose:
    - "8080"
    ports:
    - "8080:8080"
    links:
    - mongodb
    depends_on:
    - mongodb
    volumes:
    - ./data/uploads:/uploads
    - ./src:/go/src/gitlab.com/irezaa/calendar/src
    working_dir: /go/src/gitlab.com/irezaa/calendar/src
    command: bash -c "go build -o ./bin/calendar && ./bin/calendar"
    tty: true
  mcalendar-admin:
    restart: always
    container_name: "mcalendar-admin"
    image: mcalendar-admin:latest
    expose:
    - "5000"
    - "8080"
    ports:
    - "80:5000"
    links:
    - mcalendar
    - mongodb
    volumes:
    - ./admin:/src
    working_dir: /src
    command: bash -c "python /src/app.py"
  mongodb:
    restart: always
    image: mongo:latest
    container_name: "mongodb"
    environment:
    - MONGO_DATA_DIR=/mcalendar/data/db
    - MONGO_LOG_DIR=/dev/null
    volumes:
    - ./data/db:/data/db
    ports:
    - 27017:27017
    command: mongod --auth --smallfiles --logpath=/dev/null # --quiet