FROM python:latest
MAINTAINER Reza Pilehvar "graphreza@gmail.com"
COPY ./admin_requirements.txt /requirements/admin_requirements.txt
WORKDIR /requirements
RUN pip install -r /requirements/admin_requirements.txt